version: '3.4'
services:
  postgres:
    image: postgres:9.6.9
    deploy:
      replicas: 1
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow
    volumes:
      - airflow-db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.76-managment
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=airflow
      - RABBITMQ_DEFAULT_VHOST=airflow
    networks:
      - airflow
  webserver:
    image:
    deploy:
      replicas: 1
    environment:
      - AIRFLOW__CORE__FERNET__KEY=<your_key>   # If you want to put in your own, otherwise the key gets created for you
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    ports: "8080:8080"
    command: "webserver"
    networks:
      - airflow
  scheduler:
    image:
    deploy:
      replicas: 1
    environment: *webserver
    command: "scheduler"
  worker:
    image:
    deploy:
      replicas: 1
    environment: *webserver
    command: "worker"
  flower:
    image:
    deploy:
      replicas: 1
    environment:
      - *postgres
      - *rabbitmq
      - *webserver
    command: "flower"
    ports: "5555:5555"

volumes:
  airflow-db:
    external:
      name: airflow-db

networks:
  airflow:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
