version: '3.3'
services:
  postgres:
    image: postgres:9.6.9
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow
    volumes:
      - ${POSTGRES_PATH}
  rabbitmq:
    image: rabbitmq:3.76-managment
    environment:
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=airflow
      - RABBITMQ_DEFAULT_VHOST=airflow
    networks:
      - airflow
  webserver:
    image:
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - AIRFLOW__CORE__FERNET__KEY=<your_key>   # If you want to put in your own, otherwise the key gets created for you
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    ports: "8080:8080"
    command: "webserver"
    networks:
      - airflow
    volumes:
      - ${DAG_PATH}
  scheduler:
    image:
    depends_on:
      - webserver
    environment: *webserver
    command: "scheduler"
    volumes:
      - ${DAG_PATH}
  worker:
    image:
    depends_on:
      - scheduler
    environment: *webserver
    command: "worker"
    volumes:
      - ${DAG_PATH}
  flower:
    image:
    depends_on:
      - rabbitmq
    environment: *webserver
    command: "flower"
    ports: "5555:5555"
